_target_: x_vits.models.PeriodVITS

text_encoder:
  _target_: x_vits.modules.TransformerTextEncoder
  num_vocab: 100
  channels: 192
  num_layers: 6
  num_heads: 2
  dropout: 0.1
  
duration_handler:
  _target_: x_vits.modules.SupervisedDurationHandler
  duration_predictor:
    _target_: x_vits.modules.VariancePredictor
    channels: ${...text_encoder.channels}
    out_channels: 1
    kernel_size: 5
    dropout: 0.3
    num_layers: 5
  
  alignment_module: null

  length_regulator:
    _target_: x_vits.modules.HardAlignmentUpsampler

frame_prior_network:
  _target_: x_vits.modules.FramePriorNetwork
  channels: ${..text_encoder.channels}
  kernel_size: 17
  dropout: 0.1
  num_layers: 6

pitch_predictor:
  _target_: x_vits.modules.VariancePredictor
  channels: ${..text_encoder.channels}
  out_channels: 2
  kernel_size: 5
  dropout: 0.3
  num_layers: 5

flow:
  _target_: x_vits.modules.VolumePreservingFlow
  channels: ${..text_encoder.channels}
  kernel_size: 5
  dilation_rate: 1
  num_layers: 4
  num_flows: 4

posterior_encoder:
  _target_: x_vits.modules.PosteriorEncoder
  in_channels: 513
  channels: ${..text_encoder.channels}
  out_channels: ${..text_encoder.channels}
  kernel_size: 5
  dilation_rate: 1
  num_layers: 16

vocoder:
  _target_: x_vits.modules.BigVGAN
  in_channel: ${..posterior_encoder.out_channels}
  upsample_initial_channel: 512
  upsample_rates: [6, 5, 2, 2, 2]
  upsample_kernel_sizes: [12, 10, 4, 4, 4]
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  sample_rate: ${...mel.sample_rate}
  hop_length: ${...mel.hop_length}
  harmonic_num: 8

spec_tfm: ${mel}
segment_size: ${train.frame_segment_size}
