_target_: x_vits.models.XVITS

text_encoder:
  _target_: x_vits.modules.TransformerTextEncoder
  num_vocab: 100
  channels: 192
  num_layers: 6
  num_heads: 2
  dropout: 0.1
  context_channels: 384
  
duration_handler:
  _target_: x_vits.modules.SupervisedDurationHandler
  duration_predictor:
    _target_: x_vits.modules.VariancePredictor
    channels: ${...text_encoder.channels}
    out_channels: 1
    kernel_size: 5
    dropout: 0.3
    num_layers: 5
    cond_channels: ${...text_encoder.channels}
  
  alignment_module: null

  length_regulator:
    _target_: x_vits.modules.HardAlignmentUpsampler

frame_prior_network:
  _target_: x_vits.modules.FramePriorNetwork
  channels: ${..text_encoder.channels}
  kernel_size: 17
  dropout: 0.1
  num_layers: 6
  cond_channels: ${..text_encoder.channels}

pitch_predictor:
  _target_: x_vits.modules.VariancePredictor
  channels: ${..text_encoder.channels}
  out_channels: 2
  kernel_size: 5
  dropout: 0.3
  num_layers: 5
  cond_channels: ${..text_encoder.channels}

flow:
  _target_: x_vits.modules.VolumePreservingFlow
  channels: ${..text_encoder.channels}
  kernel_size: 5
  dilation_rate: 1
  num_layers: 4
  num_flows: 4
  cond_channels: ${..text_encoder.channels}

posterior_encoder:
  _target_: x_vits.modules.PosteriorEncoder
  in_channels: 513
  channels: ${..text_encoder.channels}
  out_channels: ${..text_encoder.channels}
  kernel_size: 5
  dilation_rate: 1
  num_layers: 16
  cond_channels: ${..text_encoder.channels}

vocoder:
  _target_: x_vits.modules.XVocoder
  in_channel: ${..posterior_encoder.out_channels}
  upsample_initial_channel: 512
  upsample_rates: [6, 5, 2]
  upsample_kernel_sizes: [12, 10, 4]
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  sample_rate: ${...mel.sample_rate}
  hop_length: ${...mel.hop_length}
  harmonic_num: 8
  cond_channels: ${..text_encoder.channels}

style_encoder:
  _target_: x_vits.modules.StyleEncoder
  dim_in: 16
  style_dim: ${..text_encoder.channels}
  max_conv_dim: ${..text_encoder.channels}

style_diffusion:
  _target_: x_vits.modules.AudioDiffusionConditional
  embedding_mask_proba: 0.1
  diffusion:
    _target_: x_vits.modules.KDiffusion
    net:
      _target_: x_vits.modules.Transformer1d
      num_layers: 3
      channels: ${generator.text_encoder.channels}
      num_heads: 4
      head_features: 48
      multiplier: 2
      context_embedding_features: ${generator.text_encoder.channels}
    sigma_distribution: 
      _target_: x_vits.modules.LogNormalDistribution
      mean: -3.0
      std: 1.0
    sigma_data: 0.2
    dynamic_threshold: 0.0

context_embedder:
  _target_: x_vits.modules.ContextEmbedder

spec_tfm: ${mel}
segment_size: ${train.frame_segment_size}
ref_segment_size: 96
