train:
  _target_: x_vits.datasets.SingleSpeakerDataset
  df_file: ${...path.train_df_file}
  wav_dir: ${...path.crop_wav_dir}
  cf0_dir: ${...path.cf0_dir}
  vuv_dir: ${...path.vuv_dir}
  spec_tfm: ${...mel}

valid: 
  _target_: x_vits.datasets.SingleSpeakerDataset
  df_file: ${...path.valid_df_file}
  wav_dir: ${...path.crop_wav_dir}
  cf0_dir: ${...path.cf0_dir}
  vuv_dir: ${...path.vuv_dir}
  spec_tfm: ${...mel}

collator: 
  _target_: x_vits.datasets.SingleSpeakerCollator

max_tokens: 5000
